# SPDX-License-Identifier: GPL-2.0 OR MIT

drm_xen_front-objs := xen_drm_front.o \
		      xen_drm_front_evtchnl.o \
		      xen_drm_front_shbuf.o \
		      xen_drm_front_cfg.o

obj-$(CONFIG_DRM_XEN_FRONTEND) += drm_xen_front.o
